name: Deploy node app to azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
     # Install backend dependencies
      - name: Install dependencies
        run: npm install
        working-directory: server

      - name: Build project
        run: npm run build
        working-directory: server
    # Install frontend dependencides
      - name: Install client dependencied
        run: npm install
        working-directory: frontend

      - name: Build client project
        run: npm run build
        working-directory: frontend
    #Coupy react build into server
      - name: Copy React build to server
        run: |
          mkdir -p server/public
          cp -r client/dist/* server/public

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: react-node-app
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./server